# Site settings
name: My Blog
title: My Blog
email: azrosen92@gmail.com
description: "Random thoughts, tech or otherwise"
baseurl: ""
url: "http://azrosen92.github.io" #"http://localhost:4000"

# Build settings
markdown: kramdown
permalinks: pretty
